### ISSUE TITLE
Front 에서 Controller에 Dto객체 받을때 Enum Type 오류

### ISSUE THREAD

**Issue by hshhwa** [wjdn154/ERPSystem#4]
- [문제 설명]
> RestAPI 를 이용해 Dto 객체 전송시 원하는 데이터 타입이 전송되지 않음.
- [재현 단계]
> "voucherType": "VoucherType.Withdrawal" 을 RestController의 Dto객체에 전송
- [기대 결과]
> voucherType = VoucherType.Withdrawal; 
- [실제 결과]
>voucherType = null;
- [환경]
> PostMan, Intellij
- [원인 분석]
>Json객체에서 enum타입을 그대로 전송할수 없음.
- [수정 내용]
>```public enum VoucherType {
    DEPOSIT("Deposit"), // 입금
    WITHDRAWAL("Withdrawal"), // 출금
    DEBIT("Debit"), // 차변
    CREDIT("Credit"); // 대변

    private final String name;

    VoucherType(String name) {
        this.name = name;
    }

    @JsonCreator
    public static VoucherType of(String progress) {
        return Arrays.stream(VoucherType.values())
                .filter(i -> i.name.equals(progress))
                .findAny()
                .orElse(null);
    }
}```

1. DEPOSIT 실제 EnumType에 String "Deposit" 으로 값 설정
2. @JsonCreator 어노테이션을 통해 Enum타입 호출시 String 에서 -> Enum으로 변환
- [테스트 결과]
>voucherType = VoucherType.WITHDRAWAL;
- [추가 작업]
>

**Comment by hshhwa** [comment]
해결완료

**Comment by ready-oun** [comment]
직이네요
